In [1]:
# Importing Libraries
import numpy as np
import pandas as pd

from sklearn.preprocessing import OneHotEncoder

In [2]:
# Create DataFrame using Pandas
df = pd.read_csv('data/housing.csv')

In [3]:
df.head(5)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [4]:
# Grouping and Counting based on 'ocean_proximity'
df.groupby(['ocean_proximity']).count()

longitude  latitude  housing_median_age  total_rooms  \
ocean_proximity                                                         
<1H OCEAN             9136      9136                9136         9136   
INLAND                6551      6551                6551         6551   
ISLAND                   5         5                   5            5   
NEAR BAY              2290      2290                2290         2290   
NEAR OCEAN            2658      2658                2658         2658   

                 total_bedrooms  population  households  median_income  \
ocean_proximity                                                          
<1H OCEAN                  9034        9136        9136           9136   
INLAND                     6496        6551        6551           6551   
ISLAND                        5           5           5              5   
NEAR BAY                   2270        2290        2290           2290   
NEAR OCEAN                 2628        2658        2658           2658   

                 median_house_value  
ocean_proximity                      
<1H OCEAN                      9136  
INLAND                         6551  
ISLAND                            5  
NEAR BAY                       2290  
NEAR OCEAN                     2658

In [5]:
# Sckit Learn Pre Processers for Converting String into Indexes

In [6]:
enc = OneHotEncoder(handle_unknown='ignore')

In [7]:
input_features = df[["longitude","latitude","housing_median_age","total_rooms","total_bedrooms","population","households","median_income","ocean_proximity"]]

In [8]:
input_label = df[['median_house_value']]

In [9]:
enc.fit(input_features)

OneHotEncoder(handle_unknown='ignore')

In [10]:
enc.fit(input_label)

OneHotEncoder(handle_unknown='ignore')

In [11]:
X=enc.fit(input_features).transform(input_features).toarray()

In [13]:
y=enc.fit(input_label).transform(input_label).toarray()

In [ ]:
# enc.inverse_transform(X)

In [15]:
X,y

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]))

In [17]:
from sklearn.model_selection import train_test_split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [24]:
X_train,y_train

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]))

In [ ]:
# Mapping for ocean proximity
ocean_proximity_mapping = {
    '<1H OCEAN': 0,
    'INLAND': 1,
    'ISLAND': 2,
    'NEAR BAY': 3,
    'NEAR OCEAN': 4
}

In [ ]:
df['ocean_proximity_indexed'] = df['ocean_proximity'].map(ocean_proximity_mapping)

In [ ]:
df.set_index('ocean_proximity_indexed', inplace=True)

In [ ]:
df.head(5)

In [ ]:
df.groupby(['ocean_proximity_indexed']).count()

In [ ]:
# Pareto Principle : 80 - Training , 20 - Not Training ( For Testing)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)
X_train
y_train
X_test
y_test

In [ ]:
X -> ? ==> Features
y -> ? ==> Label

In [ ]:
df

In [ ]:
X.head(5)

In [ ]:
y = df['median_house_value']

In [ ]:
y.head(5)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [ ]:
X_train.head(5)

In [ ]:
X_test.head(5)

In [ ]:
y_train.head(5)

In [ ]:
y_test.head(5)

In [ ]:
# Transformers
# Estimators
# Evalutors
# Pipeline


In [ ]:
# Estimators : Functions that allow to apply the best fitted model 

algo1 - LinearRegression
alog2 - LogisitcRegression

alog1 -> Accuary -> 90
alog2 -> Accuary -> 93
--> Alogrithm 2

In [ ]:
# Evalutors: Based on Estimators, we can figure out the Parameters from Evalutors
alog1 -> LinearRegression
Gradient


algo2 -> LogisiticRegression
Modulus

Model1 ->  93.1
-
Model3 ->  93.2

To build a model -> Transformation -> Estimators(Logisitic) -> Evaltors(Model2) 

Pipeline  -> Transformers -> Estimators(Logisitic) -> Evaulators(Model2) 

In [ ]:
Rent 
Real Value
10,000  

Predicted Value
9000

In [ ]:
Rent 
Real Value
10,000

Predicted Value
1,00,000

In [ ]:
Student
GRE/IELTS

Admission
1(yes)
0(no)



Admission
-1

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
clf = RandomForestClassifier(random_state=0)

In [ ]:
clf.fit(X_train,y_train)